// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/terms-of-use": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/terms-of-use" | "/privacy-policy";
  };
  "./App.tsx": {
    id: "App";
    page: "/";
  };
  "./pages/TermsOfUse.tsx": {
    id: "pages/TermsOfUse";
    page: "/terms-of-use";
  };
  "./pages/PrivacyPolicy.tsx": {
    id: "pages/PrivacyPolicy";
    page: "/privacy-policy";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "App": typeof import("./src/./App.tsx");
  "pages/TermsOfUse": typeof import("./src/./pages/TermsOfUse.tsx");
  "pages/PrivacyPolicy": typeof import("./src/./pages/PrivacyPolicy.tsx");
};